---
name: Contribution Suggestion
description: Suggest a new alias, feature, or improvement to the DV standardization tool
title: "[Suggestion]: "
labels: [enhancement]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary of Suggestion
      description: Briefly describe the update you are proposing.
      placeholder: e.g., Add alias "time_spent" for "task_completion_time"
    validations:
      required: true

  - type: dropdown
    id: contribution-type
    attributes:
      label: Type of Contribution
      options:
        - New DV alias
        - Dataset suggestion
        - Feature enhancement
        - LLM/semantic extension
        - UI improvement
    validations:
      required: true

  - type: input
    id: reference
    attributes:
      label: Related Publication or Dataset (optional)
      placeholder: DOI, GitHub repo, or dataset link
    validations:
      required: false
